name: Publishing Package

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  zip-files:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
    
      - name: Setup MSBuild Path
        uses:  microsoft/setup-msbuild@v1.0.2
    
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup Release directory
        #shell: cmd
        run: .\\Compile_testsuite.bat
        
      - name: Setup version
        id: getversion
        #shell: sh
        run: echo "::set-output name=version::Release_$(cat .\\Version.txt)"
      
      - uses: papeloto/action-zip@v1
        with:
          files: .\\${{ steps.getversion.outputs.version }}
          recursive: true
          dest: ${{ steps.getversion.outputs.version }}.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: Release_package
          path: ${{ github.workspace }}/${{ steps.getversion.outputs.version }}.zip
          
      #TOKEN_REPO
      #- name: Bump version and push tag to releases
        #uses: actions/create-release@v1
        #env:
          #GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
          #REPO_OWNER: Saikrishna
        #with:
          ##tag_name: v${{github.run_number}}
          #tag_name: ${{steps.create_release.outputs.string}}
          #release_name: Release Version${{github.run_number}}
         
      #- name: upload windows artifact 
        #uses: actions/upload-release-asset@v1
        #env:
          #GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
        #with:
          #upload_url: ${{ steps.create_release.outputs.upload_url }}
          #asset_path: ${{ github.workspace }}/${{ steps.getversion.outputs.version }}.zip
          #asset_name: ${{ steps.getversion.outputs.version }}.zip
          #asset_content_type: application/zip
