name: Publishing Package

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
    
      - name: Setup MSBuild Path
        uses:  microsoft/setup-msbuild@v1.0.2
    
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup Release directory
        run: .\\Compile_testsuite.bat
        
      - name: Setup version
        id: getversion
        run: echo "::set-output name=version::Release_$(cat .\\Version.txt)"
      
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
      #- uses: papeloto/action-zip@v1
        with:
          files: .\\${{ steps.getversion.outputs.version }}
          recursive: true
          dest: ${{ steps.getversion.outputs.version }}.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: Release_package
          path: ${{ github.workspace }}/${{ steps.getversion.outputs.version }}.zip
     
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.getversion.outputs.version }}.zip"
          token: ${{ secrets.TOKEN_REPO }}
