name: Publishing Package
on:
  push:
    branches: [main]

jobs:
  zip-files:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
    
      - name: Setup MSBuild Path
        uses:  microsoft/setup-msbuild@v1.0.2
    
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup Release directory
        #shell: cmd
        run: .\\Compile_testsuite.bat
        
      - uses: papeloto/action-zip@v1
        with:
          files: .\\Release_1.00
          recursive: true
          dest: Release_1.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: Release_package
          path: ${{ github.workspace }}/Release_1.zip
          
      #TOKEN_REPO
      - name: Bump version and push tag
        #uses: anothrNick/github-tag-action@master
        #env:
          #GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
          #REPO_OWNER: Saikrishna
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}
