name: SelfhostedRunner Test
#Defining the "On" using manual trigger
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
 
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    
    - name: Setup MSBuild Path
      uses:  microsoft/setup-msbuild@v1.0.2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    #- name: Setup Release directory
      #shell: sh
      #run: .\\Compile_testsuite.bat
      
    #- name: Setup version
      #id: getversion
      #run: echo "::set-output name=version::$(cat Version)"
      
    - name: Setting Path
      shell: sh
      working-directory: ".\\Release_**\\run"
      run: pwd
      
    #- name: Run Boss script
      #working-directory: ".\\Release_${{ steps.getversion.outputs.version }}\\run"
      #shell: sh
      #run: .\\MSOffice_Test_Automation.bat
      
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference

    #- name: Build the solution
      #shell: sh
      #run: MSBuild.exe .\\Word_JenkaLoad\\Word_JenkaLoad.sln //p:Configuration=Release //p:Platform="Any CPU"
